name: Executar testes Cucumber com Allure

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0

    - name: Instalar dependências
      run: bundle install --jobs 4 --retry 3

    - name: Executar testes Cucumber com Allure
      run: |
        rake service[@pipeline]
      working-directory: ${{ github.workspace }}

    - name: Gerar relatório Allure
      uses: fescobar/allure-report-action@v1.1.1
      with:
        allure-version: '2.14.0'
        results: allure-results
        output: allure-report

    - name: Compactar relatório Allure em um arquivo ZIP
      run: zip -r allure-report.zip allure-report
      working-directory: ${{ github.workspace }}

    - name: Fazer upload do arquivo ZIP do relatório Allure como artefato
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report.zip